### ISSUE TITLE
cannot start API service

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/api#108]
It seems to me that APi requires at least one user in etcd. Is there any documentation how to do this without running API? Also we should consider that ordinary user will not touch directly Etcd content.

```
/usr/bin/puma -e production --dir /usr/share/tendrl-api/
Puma starting in single mode...
* Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: production
! Unable to load application: NameError: uninitialized constant Tendrl::Validator::UserValidator::ActiveModel
/usr/share/tendrl-api/lib/tendrl/validators/user_validator.rb:4:in `<class:UserValidator>': uninitialized constant Tendrl::Validator::UserValidator::ActiveModel (NameError)
        from /usr/share/tendrl-api/lib/tendrl/validators/user_validator.rb:3:in `<module:Validator>'
        from /usr/share/tendrl-api/lib/tendrl/validators/user_validator.rb:2:in `<module:Tendrl>'
        from /usr/share/tendrl-api/lib/tendrl/validators/user_validator.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/tendrl-api/lib/tendrl.rb:29:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/tendrl-api/app/controllers/application_controller.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from config.ru:2:in `block in <main>'
        from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
        from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
        from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
        from /usr/bin/puma:23:in `load'
        from /usr/bin/puma:23:in `<main>'
```

**Comment by anivargi** [comment]
@mkudlej This error is not related to default user being present, it is to do with a RPM dependency not being required. The fixes is at https://github.com/Tendrl/api/pull/109

For generating a default user, there is documentation present at the following location.
https://github.com/Tendrl/api/blob/master/docs/users.adoc#create-admin-user

**Comment by mkudlej** [comment]
All new required packages are installed:
```
$ rpm -qa | grep bcrypt
rubygem-bcrypt-3.1.10-6.el7.x86_64
$ rpm -qa | grep active
rubygem-activesupport-4.2.6-1.el7.noarch
rubygem-activemodel-4.2.6-3.el7.noarch
```
I've tried to load default user to etcd:
```
$ cd /usr/share/tendrl-api
$ bundle exec rake etcd:load_admin
Your bundle is locked to json (1.8.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of json (1.8.3) has removed it. You'll need to update your bundle to a different version of json (1.8.3) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.
```
How could I fix this, please?

**Comment by anivargi** [comment]
@mkudlej Looks like the package does not have the Rakefile in it which is required for running the task, let me ask @TimothyAsir to add it to the packaging.

**Comment by anivargi** [comment]
@mkudlej you can try with the latest build. Also updated the doc to generate the default admin https://github.com/Tendrl/api/blob/master/docs/users.adoc#create-admin-user

**Comment by mkudlej** [comment]
It works with
```
tendrl-performance-monitoring-1.2.1-03_22_2017_16_43_46.noarch
tendrl-commons-1.2.1-03_22_2017_16_50_15.noarch
tendrl-api-doc-1.2.1-03_22_2017_17_03_14.noarch
tendrl-api-1.2.1-03_22_2017_17_03_14.noarch
tendrl-dashboard-1.2.1-03_22_2017_04_11_04.noarch
tendrl-api-httpd-1.2.1-03_22_2017_17_03_14.noarch
```
--> Close

**Comment by mkudlej** [comment]
This is solved with:
```
tendrl-commons-1.2.1-03_24_2017_06_33_41.noarch
tendrl-api-httpd-1.2.1-03_24_2017_01_51_03.noarch
tendrl-api-1.2.1-03_24_2017_01_51_03.noarch
tendrl-performance-monitoring-1.2.1-03_24_2017_06_28_22.noarch
tendrl-api-doc-1.2.1-03_24_2017_01_51_03.noarch
tendrl-dashboard-1.2.1-03_24_2017_06_59_47.noarch
```
