### ISSUE TITLE
GetNodeList API call is not working

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#113]
GetNodeList call returns `500 Internal Server Error`

```
# curl -X GET -i -k -H "Authorization: Bearer <token>" <hostname>/api/1.0/GetNodeList; echo ""
HTTP/1.1 500 Internal Server Error
Date: Thu, 23 Mar 2017 12:57:08 GMT
Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5
Content-Type: text/html;charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
Access-Control-Allow-Headers: Origin,Content-Type,Accept,Authorization,X-Requested-With
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 30
Connection: close

<h1>Internal Server Error</h1>
```

Used Packages:
tendrl-api-1.2.1-03_22_2017_17_03_14.noarch
tendrl-dashboard-1.2.1-03_23_2017_04_29_50.noarch
tendrl-commons-1.2.1-03_23_2017_12_30_14.noarch
tendrl-api-doc-1.2.1-03_22_2017_17_03_14.noarch
tendrl-performance-monitoring-1.2.1-03_22_2017_16_43_46.noarch
tendrl-api-httpd-1.2.1-03_22_2017_17_03_14.noarch

**Comment by mkudlej** [comment]
Stack trace from api process:
```
RuntimeError - This is not a directory, cant have children:
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/node.rb:37:in `children'
	/usr/share/tendrl-api/app/controllers/application_controller.rb:97:in `recurse'
	/usr/share/tendrl-api/app/controllers/authenticated_users_controller.rb:39:in `monitoring'
	/usr/share/tendrl-api/app/controllers/nodes_controller.rb:96:in `load_stats'
	/usr/share/tendrl-api/app/controllers/nodes_controller.rb:32:in `block in <class:NodesController>'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
10.40.3.40 - - [23/Mar/2017:12:59:09 +0000] "GET /1.0/GetNodeList HTTP/1.1" 500 30 0.3590
```

**Comment by anivargi** [comment]
The monitoring configuration has completely changed and hence the API cannot read the settings required to fetch the monitoring data.
@anmolbabu can explain more about the changes and how we can integrate it make it working with the API again.

Meanwhile I am going to comment out the stats which load from the monitoring API for us to proceed forward.

**Comment by anmolbabu** [comment]
The change is in the path where the config is loaded in etcd(_NS/node_monitoring/config) and as per https://github.com/Tendrl/performance-monitoring/pull/71#discussion_r106850436 I am not sure how api missed this communication as this change is going to happen across all modules.
I think @r0h4n can add more....

**Comment by anmolbabu** [comment]
Moreover these changes are being tested and fixed The change is as recent as day before yesterday in performance-monitoring(https://github.com/Tendrl/performance-monitoring/pull/71) and alerting(https://github.com/Tendrl/alerting/pull/41) and fixes in some areas are in progress..

**Comment by anivargi** [comment]
@anmolbabu The path changes were made, but the structure of what is returned from the path is what is creating the problem.

**Comment by anmolbabu** [comment]
>>> etcd_client.read('/_NS/performance_monitoring/config/data', recursive=True)
<class 'etcd.EtcdResult'>({'newKey': False, 'raft_index': 1740832, '_children': [{u'createdIndex': 345605, u'modifiedIndex': 345605, u'value': u"['tendrl/performance-monitoring']", u'key': u'/_NS/performance_monitoring/config/data/tags'}, {u'createdIndex': 345606, u'modifiedIndex': 345606, u'value': u'xx.xx.xx.xx', u'key': u'/_NS/performance_monitoring/config/data/time_series_db_server'}, {u'createdIndex': 345597, u'modifiedIndex': 345597, u'value': u'5000', u'key': u'/_NS/performance_monitoring/config/data/api_server_port'}, {u'createdIndex': 345598, u'modifiedIndex': 345598, u'value': u"{'node': {'memory': {'Failure': 90, 'Warning': 80}, 'mount_point': {'Failure': 90, 'Warning': 80}, 'swap': {'Failure': 70, 'Warning': 50}, 'cpu': {'Failure': 90, 'Warning': 80}}, 'ceph': {'cluster_utilization': {'Failure': 90, 'Warning': 75}, 'osd_utilization': {'Failure': 95, 'Warning': 85}, 'pool_utilization': {'Failure': 90, 'Warning': 75}}, 'glusterfs': {'cluster_utilization': {'Failure': 90, 'Warning': 75}, 'volume_utilization': {'Failure': 90, 'Warning': 75}}}", u'key': u'/_NS/performance_monitoring/config/data/thresholds'}, {u'createdIndex': 345600, u'modifiedIndex': 345600, u'value': u'10080', u'key': u'/_NS/performance_monitoring/config/data/time_series_db_port'}, {u'createdIndex': 345602, u'modifiedIndex': 345602, u'value': u'/etc/tendrl/performance-monitoring/performance-monitoring_logging.yaml', u'key': u'/_NS/performance_monitoring/config/data/log_cfg_path'}, {u'createdIndex': 345603, u'modifiedIndex': 345603, u'value': u'2379', u'key': u'/_NS/performance_monitoring/config/data/etcd_port'}, {u'createdIndex': 345604, u'modifiedIndex': 345604, u'value': u'dhcpxx-xx.lab.eng.blr.redhat.com', u'key': u'/_NS/performance_monitoring/config/data/master_name'}, {u'createdIndex': 345594, u'modifiedIndex': 345594, u'value': u'600', u'key': u'/_NS/performance_monitoring/config/data/interval'}, {u'createdIndex': 345595, u'modifiedIndex': 345595, u'value': u'DEBUG', u'key': u'/_NS/performance_monitoring/config/data/log_level'}, {u'createdIndex': 345596, u'modifiedIndex': 345596, u'value': u'xx.xx.xx.xx', u'key': u'/_NS/performance_monitoring/config/data/etcd_connection'}, {u'createdIndex': 345599, u'modifiedIndex': 345599, u'value': u'dhcpxx-xx.lab.eng.blr.redhat.com', u'key': u'/_NS/performance_monitoring/config/data/api_server_addr'}, {u'createdIndex': 345601, u'modifiedIndex': 345601, u'value': u'graphite', u'key': u'/_NS/performance_monitoring/sconfig/data/time_series_db'}], 'createdIndex': 6, 'modifiedIndex': 6, 'value': None, 'etcd_index': 904917, 'expiration': None, 'key': u'/_NS/performance_monitoring/config/data', 'ttl': None, 'action': u'get', 'dir': True})


This is the response I see and I changed only the path.. So, if anything needs to be fixed, Please let me know what needs to be fixed and I shall do the same...

**Comment by anivargi** [comment]
The @Tendrl/tendrl-core team is working on some more changes to the definitions files, due to which the API is affected and will be unstable. 

Once the definitions are stable and finalized the API can change things accordingly.

**Comment by mkudlej** [comment]
Tested with 
```
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.1-03_31_2017_01_51_34.noarch
tendrl-api-doc-1.2.1-03_31_2017_01_51_34.noarch
tendrl-api-httpd-1.2.1-03_31_2017_01_51_34.noarch
tendrl-commons-1.2.1-03_31_2017_06_03_08.noarch
tendrl-dashboard-1.2.1-03_31_2017_04_11_03.noarch
tendrl-performance-monitoring-1.2.1-03_31_2017_03_02_02.noarch
```
and it works -> close

**Comment by mkudlej** [comment]
@ltrilety Please close.

**Comment by r0h4n** [comment]
@mkudlej please provide NVR of tendrl-node-agent as well

**Comment by mkudlej** [comment]
@r0h4n 
on Ceph nodes:
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
python-etcd-0.4.3-1.noarch
tendrl-commons-1.2.1-03_31_2017_06_03_08.noarch
tendrl-node-agent-1.2.1-03_31_2017_06_35_45.noarch
tendrl-node-monitoring-1.2.1-03_31_2017_00_37_03.noarch
```
