### ISSUE TITLE
GetNodeList bad number of nodes for detected clusters

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#132]
Whilst it seems that cluster is always detected the number of nodes is not correct as some of them have not `detectedcluster` section in `GetNodeList` API call response. In my case the section is missing for `ltrilety-usm1-gl2.usmqe.lab.eng.brq.redhat.com` and so I have 3 nodes shown in clusters section instead of 4. Stop and start of `tendrl-node-agent` on the machine fix the issue.

That said it seems in corner case it could happen that cluster will not be detected as before in https://github.com/Tendrl/api/issues/86.
 
```
{
"nodes": [
  {
"fqdn": "ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com",
"machine_id": "d3c4d066d7074faf921deec86f075d7a",
"node_id": "2f043c42-c5e8-401e-ad27-dbd5be52e781",
"status": "UP",
"tags": "["provisioner/ceph", "tendrl/central-store", "tendrl/server", "tendrl/node"]",
"networks": {...},
"messages": {...},
"platform": {...},
"cpu": {...},
"memory": {...},
"disks": {...},
"tendrlcontext": {...},
"os": {...},
"stats": {...}
},
  {
"tags": "["tendrl/node"]",
"fqdn": "ltrilety-usm1-gl2.usmqe.lab.eng.brq.redhat.com",
"machine_id": "16308fc022df4c97a79b8d793bb9444d",
"node_id": "6fb025b9-0e79-4cdb-8a00-f94a449f7e01",
"status": "UP",
"tendrlcontext": {...},
"platform": {...},
"os": {...},
"cpu": {...},
"memory": {...},
"messages": {...},
"disks": {...},
"stats": {...}
},
  {
"fqdn": "ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com",
"machine_id": "006cb4885b194c4a8890801571fd678d",
"node_id": "efd31949-8758-4e51-a1c3-aecca75b1f7d",
"status": "UP",
"tags": "["gluster/server", "tendrl/node"]",
"tendrlcontext": {...},
"os": {...},
"disks": {...},
"detectedcluster": {...},
"platform": {...},
"cpu": {...},
"memory": {...},
"messages": {...},
"networks": {...},
"stats": {...}
},
  {
"status": "UP",
"tags": "["gluster/server", "tendrl/node"]",
"fqdn": "ltrilety-usm1-gl3.usmqe.lab.eng.brq.redhat.com",
"machine_id": "782e1bf29b244e8d8b7b420fcb94ed09",
"node_id": "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
"tendrlcontext": {...},
"os": {...},
"messages": {...},
"cpu": {...},
"memory": {...},
"networks": {...},
"disks": {...},
"detectedcluster": {...},
"platform": {...},
"stats": {...}
},
  {
"node_id": "99811961-0cf7-439c-b5c6-7f609967012f",
"status": "UP",
"tags": "["gluster/server", "tendrl/node"]",
"fqdn": "ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com",
"machine_id": "8d72c3ef6f5a40e0b65f982df1b2522f",
"tendrlcontext": {...},
"platform": {...},
"cpu": {...},
"memory": {...},
"messages": {...},
"detectedcluster": {...},
"os": {...},
"networks": {...},
"stats": {...}
}
],
"clusters": [
  {
"cluster_id": "4107e32c33f45d4e1995f61e43159eadf7bd8a34938b47dca702823728064ef9",
"sds_name": "glusterfs",
"sds_version": "3.9.1",
"node_ids": [
  "efd31949-8758-4e51-a1c3-aecca75b1f7d",
  "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
  "99811961-0cf7-439c-b5c6-7f609967012f"
],
}
],
}
```

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by shtripat** [comment]
@ltrilety were there some errors in node-agent logs where detected cluster field was empty (and got populated after re-start)?

**Comment by ltrilety** [comment]
@shtripat that's a valid and good question, unfortunately I have to reinstall my machines. I'll provide an answer if that happens again.

**Comment by ltrilety** [comment]
@shtripat and now the corner case happens to me, no node has `detectedcluster` section.

Anyway this errors can be found for tendrl-node-agent before I stop it
```
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/central_store/__init__.py", line 
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: ttl=NS.config.data['message_retention_time'])
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", line 101, in s
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.client.write(item['key'], item['value'], quorum=True)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 465, in write
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: response = self.api_execute(path, method, params=params)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: return self._handle_server_response(response)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_respon
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: etcd.EtcdError.handle(r)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: raise exc(msg, payload)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: EtcdException: Raft Internal Error : etcdserver: request timed out
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: <Greenlet at 0x170da50: <bound method MessageHandler.read_socket of <MessageHandler at 0x1
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: Traceback (most recent call last):
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: result = self._run(*self.args, **self.kwargs)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py", line 331,
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: "exception": ex}
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 18, in __init__
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: Logger(message)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/logger.py", line 25, in __init__
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.push_event()
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/logger.py", line 95, in push_event
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: caller=self.message.caller
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/objects/message/__init__.py", lin
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: super(Message, self).save(update=False)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", line 95, in sa
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.__class__.__name__.lower())(cls_etcd())
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/central_store/__init__.py", line 
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: ttl=NS.config.data['message_retention_time'])
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", line 101, in s
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.client.write(item['key'], item['value'], quorum=True)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 465, in write
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: response = self.api_execute(path, method, params=params)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: return self._handle_server_response(response)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_respon
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: etcd.EtcdError.handle(r)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: raise exc(msg, payload)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: EtcdException: Raft Internal Error : etcdserver: request timed out
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: <NodeAgentSyncThread at 0x170d0f0> failed with EtcdException
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: Traceback (most recent call last):
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: result = self._run(*self.args, **self.kwargs)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 132, in _run
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: "exception": ex
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 18, in __init__
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: Logger(message)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/logger.py", line 25, in __init__
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.push_event()
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/logger.py", line 95, in push_event
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: caller=self.message.caller
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/objects/message/__init__.py", lin
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: super(Message, self).save(update=False)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", line 95, in sa
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.__class__.__name__.lower())(cls_etcd())
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/central_store/__init__.py", line 
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: ttl=NS.config.data['message_retention_time'])
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", line 101, in s
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: self.client.write(item['key'], item['value'], quorum=True)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 465, in write
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: response = self.api_execute(path, method, params=params)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: return self._handle_server_response(response)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_respon
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: etcd.EtcdError.handle(r)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: raise exc(msg, payload)
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: EtcdException: Raft Internal Error : etcdserver: request timed out
Apr 06 04:27:22 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: <JobConsumerThread at 0x170d4b0> failed with EtcdException
Apr 06 04:27:40 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-age[10086]: 2017-04-06 04:27:22.482156+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tendrl
Apr 06 04:27:40 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10086]: 2017-04-06 04:27:22.482156+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tend
Apr 06 07:21:33 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com systemd[1]: Stopping A python agent local to every managed storage node in the sds cluster...
```

Checked with:
tendrl-api-doc-1.2.2-04_06_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.2-04_06_2017_03_02_03.noarch
tendrl-api-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-httpd-1.2.2-04_06_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch

**Comment by shtripat** [comment]
@ltrilety thanks for the logs. It clearly looks an issue with etcd server. May be related to load and too many writes to etcd. https://github.com/coreos/etcd/issues/3864

@r0h4n thoughts?

**Comment by r0h4n** [comment]
Is this bug still valid?
