### ISSUE TITLE
rake etcd:load_admin fails with Connection refused - connect(2)

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/api#170]
etcd-3.1.3-1.el7.x86_64
tendrl-api-1.2.3-05_09_2017_13_23_12.noarch
tendrl-api-doc-1.2.3-05_09_2017_13_23_12.noarch
tendrl-api-httpd-1.2.3-05_09_2017_13_23_12.noarch

On my testbed I can create keys with etcdctl mkdir /foo and list them but when I try to create the admin user I get:

[root@tendrl tendrl-api]# RACK_ENV=production;rake etcd:load_admin --trace
** Invoke etcd:load_admin (first_time)
** Execute etcd:load_admin
"Generating default Tendrl admin"
rake aborted!
Connection refused - connect(2)
/usr/share/ruby/net/http.rb:878:in `initialize'
/usr/share/ruby/net/http.rb:878:in `open'
/usr/share/ruby/net/http.rb:878:in `block in connect'
/usr/share/ruby/timeout.rb:52:in `timeout'
/usr/share/ruby/net/http.rb:877:in `connect'
/usr/share/ruby/net/http.rb:862:in `do_start'
/usr/share/ruby/net/http.rb:851:in `start'
/usr/share/ruby/net/http.rb:1373:in `request'
/usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
/usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
/usr/share/tendrl-api/lib/tendrl/user.rb:77:in `find'
/usr/share/tendrl-api/Rakefile:19:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:228:in `call'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:228:in `block in execute'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:223:in `each'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:223:in `execute'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:143:in `invoke_task'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `each'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `block in top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:110:in `run_with_threads'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:95:in `top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:73:in `block in run'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:70:in `run'
/bin/rake:37:in `<main>'
Tasks: TOP => etcd:load_admin

**Comment by japplewhite** [comment]
appears to be related to the use of localhost in the usmqe-setup process. closing
