### ISSUE TITLE
user cannot login after package update

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/api#171]
I've updated api package and I was not able to login and password which are the same as I've used with previous package. I have to delete user from Etcd and load it again with Rake.
There traceback in Apid output:
```
/usr/bin/puma -e production --dir /usr/share/tendrl-api/
Puma starting in single mode...
* Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
Errno::ECONNREFUSED - Connection refused - connect(2):
	/usr/share/ruby/net/http.rb:878:in `initialize'
	/usr/share/ruby/net/http.rb:878:in `open'
	/usr/share/ruby/net/http.rb:878:in `block in connect'
	/usr/share/ruby/timeout.rb:52:in `timeout'
	/usr/share/ruby/net/http.rb:877:in `connect'
	/usr/share/ruby/net/http.rb:862:in `do_start'
	/usr/share/ruby/net/http.rb:851:in `start'
	/usr/share/ruby/net/http.rb:1373:in `request'
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
	/usr/share/tendrl-api/lib/tendrl/user.rb:77:in `find'
	/usr/share/tendrl-api/lib/tendrl/user.rb:123:in `authenticate'
	/usr/share/tendrl-api/app/controllers/sessions_controller.rb:7:in `block in <class:SessionsController>'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
10.40.204.34 - - [11/May/2017:05:42:17 +0000] "POST /1.0/login HTTP/1.1" 500 30 0.0174
```
I've used as new packages
```
ceph-ansible-2.2.0-94.gd8c9e13.el7.noarch
ceph-installer-1.3.0-7.g9289910.el7.noarch
etcd-3.1.3-1.el7.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.3-05_11_2017_01_51_04.noarch
tendrl-api-doc-1.2.3-05_11_2017_01_51_04.noarch
tendrl-api-httpd-1.2.3-05_11_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_11_2017_05_13_05.noarch
tendrl-dashboard-1.2.3-05_11_2017_04_11_05.noarch
tendrl-node-agent-1.2.3-05_11_2017_00_01_05.noarch
tendrl-performance-monitoring-1.2.3-05_11_2017_03_02_05.noarch
```
Old packages were one day older that previous list. I've restarted machines after package update.

**Comment by mkudlej** [comment]
And now I'm not able to load admin user:
```
RACK_ENV=production rake etcd:load_admin --trace
** Invoke etcd:load_admin (first_time)
** Execute etcd:load_admin
"Generating default Tendrl admin"
rake aborted!
Connection refused - connect(2)
/usr/share/ruby/net/http.rb:878:in `initialize'
/usr/share/ruby/net/http.rb:878:in `open'
/usr/share/ruby/net/http.rb:878:in `block in connect'
/usr/share/ruby/timeout.rb:52:in `timeout'
/usr/share/ruby/net/http.rb:877:in `connect'
/usr/share/ruby/net/http.rb:862:in `do_start'
/usr/share/ruby/net/http.rb:851:in `start'
/usr/share/ruby/net/http.rb:1373:in `request'
/usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
/usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
/usr/share/tendrl-api/lib/tendrl/user.rb:77:in `find'
/usr/share/tendrl-api/Rakefile:19:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:228:in `call'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:228:in `block in execute'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:223:in `each'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:223:in `execute'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
/usr/share/gems/gems/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:143:in `invoke_task'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `each'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:101:in `block in top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:110:in `run_with_threads'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:95:in `top_level'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:73:in `block in run'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/share/gems/gems/rake-0.9.6/lib/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
Tasks: TOP => etcd:load_admin
```

**Comment by mkudlej** [comment]
It seems that this happen because of misconfiguration because upgrade replaced configuration files.
