### ISSUE TITLE
Strage traceback (NoMethodError: undefined method `stop' for nil:NilClass) during tendrl-ansible driven installation of Tendrl

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#245]
## Description

When I install last stable [Tendrl release (version 1.5.0)](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.0-(summary)) using [tendrl-ansible (current master tailored for 1.5.0)](https://github.com/Tendrl/tendrl-ansible/tree/0a09c863a8cfbc610d559900b318cd576890ddd1), I see strange errors in tendrl-api logs.

## Version

Tendrl 1.5.0 on CentOS Linux release 7.3.1611 (Core)

```
# rpm -qa | grep tendrl
tendrl-monitoring-integration-1.0.0-1.el7.centos.noarch
tendrl-commons-1.5.0-1.el7.centos.noarch
tendrl-api-1.5.0-1.el7.centos.noarch
tendrl-node-agent-1.5.0-1.el7.centos.noarch
tendrl-ui-1.5.0-1.el7.centos.noarch
tendrl-api-httpd-1.5.0-1.el7.centos.noarch
# rpm -qa | egrep '(grafana|graphite|gluster|gdeploy|collectd|etcd|puma)'
graphite-web-0.9.16-1.el7.noarch
etcd-3.1.9-1.el7.x86_64
grafana-4.4.3-1.x86_64
python-etcd-0.4.5-1.noarch
collectd-5.7.1-2.el7.x86_64
collectd-ping-5.7.1-2.el7.x86_64
rubygem-puma-3.6.0-1.el7.centos.x86_64
rubygem-etcd-0.3.0-1.el7.centos.noarch
```

## Steps to reproduce

1. With tendrl-ansible, install Tendrl stable release 1.5.0
2. On Tendrl Server machine, check logs of tendrl-api: `journalctl -u tendrl-api.service`

## Actual Result

I see errors and traceback lines in tendrl-api logs:

```
[root@mbukatov-usm1-server ~]# journalctl -u tendrl-api.service
-- Logs begin at Tue 2017-08-22 14:29:50 UTC, end at Tue 2017-08-22 15:35:36 UTC. --
Aug 22 15:19:09 mbukatov-usm1-server.example.com systemd[1]: Started Tendrl Api Daemon.
Aug 22 15:19:09 mbukatov-usm1-server.example.com systemd[1]: Starting Tendrl Api Daemon...
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: Puma starting in single mode...
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: * Min threads: 0, max threads: 16
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: * Environment: production
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: * Listening on tcp://0.0.0.0:9292
Aug 22 15:19:10 mbukatov-usm1-server.example.com puma[13270]: Use Ctrl-C to stop
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Stopping Tendrl Api Daemon...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[13270]: - Gracefully stopping, waiting for requests to finish
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[13270]: === puma shutdown: 2017-08-22 15:22:07 +0000 ===
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[13270]: - Goodbye!
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Started Tendrl Api Daemon.
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Starting Tendrl Api Daemon...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: Puma starting in single mode...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: * Min threads: 0, max threads: 16
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: * Environment: production
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Stopping Tendrl Api Daemon...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: ! Unable to load application: NoMethodError: undefined method `stop' for nil:NilClass
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: /usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:16:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:146:in `stop'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:382:in `block in setup_signals'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `call'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/inflections.rb:1:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies/autoload.rb:1:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support.rb:25:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/activemodel-4.2.6/lib/active_model.rb:24:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/tendrl-api/lib/tendrl.rb:12:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/tendrl-api/app/controllers/application_controller.rb:1:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from config.ru:2:in `block in <main>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from config.ru:in `new'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from config.ru:in `<main>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/bin/puma:23:in `load'
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16111]: from /usr/bin/puma:23:in `<main>'
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: tendrl-api.service: main process exited, code=exited, status=1/FAILURE
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Unit tendrl-api.service entered failed state.
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: tendrl-api.service failed.
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Started Tendrl Api Daemon.
Aug 22 15:22:07 mbukatov-usm1-server.example.com systemd[1]: Starting Tendrl Api Daemon...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16171]: Puma starting in single mode...
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16171]: * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16171]: * Min threads: 0, max threads: 16
Aug 22 15:22:07 mbukatov-usm1-server.example.com puma[16171]: * Environment: production
Aug 22 15:22:08 mbukatov-usm1-server.example.com puma[16171]: * Listening on tcp://0.0.0.0:9292
Aug 22 15:22:08 mbukatov-usm1-server.example.com puma[16171]: Use Ctrl-C to stop
```

Here is the 1st traceback, extracted from the logs posted above:

```
! Unable to load application: NoMethodError: undefined method `stop' for nil:NilClass
/usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:16:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:146:in `stop'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:382:in `block in setup_signals'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `call'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/inflections.rb:1:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies/autoload.rb:1:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/gems/gems/activesupport-4.2.6/lib/active_support.rb:25:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/gems/gems/activemodel-4.2.6/lib/active_model.rb:24:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
from /usr/share/tendrl-api/lib/tendrl.rb:12:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/tendrl-api/app/controllers/application_controller.rb:1:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from config.ru:2:in `block in <main>'
from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
from config.ru:in `new'
from config.ru:in `<main>'
from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
from /usr/bin/puma:23:in `load'
from /usr/bin/puma:23:in `<main>'
```

## Expected Result

There should be no traceback/error in tendrl-api logs.

**Comment by mbukatov** [comment]
I will check if this can be reproduced with current builds from master branch (upcoming next milestone) during work on https://github.com/Tendrl/tendrl-ansible/issues/23

**Comment by mbukatov** [comment]
Rechecking with `tendrl-api-1.5.2-20170921T125939.61d8945.noarch`, when I have installed tendrl and imported cluster and I don't see the stack traces any more:

```
# journalctl -u tendrl-api.service
-- Logs begin at Tue 2017-09-26 05:36:25 UTC, end at Tue 2017-09-26 08:18:40 UTC. --
Sep 26 05:53:15 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Started Tendrl Api Daemon.
Sep 26 05:53:15 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] Puma starting in cluster mode...
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Min threads: 8, max threads: 8
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Environment: production
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Process workers: 2
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Preloading application
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] * Listening on tcp://127.0.0.1:9292
Sep 26 05:53:16 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[5402]: [5402] Use Ctrl-C to stop
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Started Tendrl Api Daemon.
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] Puma starting in cluster mode...
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Min threads: 8, max threads: 8
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Environment: production
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Process workers: 2
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Preloading application
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] * Listening on tcp://127.0.0.1:9292
Sep 26 05:57:32 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[8850]: [8850] Use Ctrl-C to stop
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Started Tendrl Api Daemon.
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] Puma starting in cluster mode...
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Min threads: 8, max threads: 8
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Environment: production
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Process workers: 2
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Preloading application
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] * Listening on tcp://127.0.0.1:9292
Sep 26 05:57:34 mbukatov-usm1-server.usmqe.lab.eng.brq.redhat.com puma[9014]: [9014] Use Ctrl-C to stop

```

**Comment by mbukatov** [comment]
Based on verification described in previous comment, I'm closing the issue.
