### ISSUE TITLE
Importing cluster immediately after installation fails

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#353]
Cluster import performed via API by our test in CentOS CI is failing with following error:
``Failure in Job 3e68fb46-97a0-4f36-8269-e2ad9a0f75b8 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 218, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 56, in run "import" % integration_id) FlowExecutionFailedError: Cluster with integration_id (87e31009-40ee-4678-9733-07970cfc4672) not found, cannot import``

Which is quite strange error, because cluster with id `87e31009-40ee-4678-9733-07970cfc4672` exists and is visible on the Clusters page.

![tendrl-clusters-page](https://user-images.githubusercontent.com/4759779/36149905-dc1d528e-10c1-11e8-8f4d-477f2beff334.png)

![tendrl-task-page-importcluster-error](https://user-images.githubusercontent.com/4759779/36149972-2c890100-10c2-11e8-9abd-5e6255719a9d.png)

There seems to be some problem with timing, because in this case, the import cluster test was launched immediately after the installation finish. If I'll put `sleep 30` between the installation and test job, it works correctly.

It seems to me like low priority issue, because it is not likely visible on real world scenario - user interaction will be probably slower than our automation.

---------------------------------------
Version of tendrl packages:
```
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-api-1.5.5-1.el7.centos.noarch
tendrl-api-httpd-1.5.5-1.el7.centos.noarch
tendrl-commons-1.5.5-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.5-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.5.5-1.el7.centos.noarch
tendrl-node-agent-1.5.5-1.el7.centos.noarch
tendrl-notifier-1.5.5-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.5.5-1.el7.centos.noarch
```

**Comment by dahorak** [comment]
I was able to reproduce it on my VMs, simply I have to wait until the cluster appear in the Tendrl web UI and once it is there, immediately try to import it.

**Comment by GowthamShanmugam** [comment]
is this issue is still valid?
