### ISSUE TITLE
Internal Server Error when trying to get log of a job via API

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#95]
I get `500 Internal Server Error` when I try to get log of a job from API. I tried to call `hostname/api/1.0/jobs/job_id/logs?type=log_type` (as defined in response of `hostname/api/1.0/jobs/job_id`) and `hostname/api/1.0/jobs/job_id/logs`.

`# journalctl -u tendrl-apid`
```
-- Logs begin at Wed 2017-03-08 10:10:08 UTC, end at Wed 2017-03-08 11:50:57 UTC. --
Mar 08 10:33:42 hostname systemd[1]: Started Tendrl Api Daemon.
Mar 08 10:33:42 hostname systemd[1]: Starting Tendrl Api Daemon...
Mar 08 10:33:42 hostname puma[21396]: Puma starting in single mode...
Mar 08 10:33:42 hostname puma[21396]: * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Mar 08 10:33:42 hostname puma[21396]: * Min threads: 0, max threads: 16
Mar 08 10:33:42 hostname puma[21396]: * Environment: production
Mar 08 10:33:42 hostname puma[21396]: * Listening on tcp://0.0.0.0:9292
Mar 08 10:33:42 hostname puma[21396]: Use Ctrl-C to stop
Mar 08 11:45:04 hostname puma[21396]: 10.40.3.22 - - [08/Mar/2017:11:45:04 +0000] "GET //1.0/jobs HTTP/1.1" 200 2 0.0365
Mar 08 11:45:08 hostname puma[21396]: 10.40.3.22 - - [08/Mar/2017:11:45:08 +0000] "GET //1.0/jobs HTTP/1.1" 200 2 0.0214
Mar 08 11:46:30 hostname puma[21396]: 10.34.125.33 - - [08/Mar/2017:11:46:30 +0000] "GET /1.0/GetNodeList HTTP/1.1" 200 33912 0.5138
Mar 08 11:46:31 hostname puma[21396]: 10.34.125.33 - - [08/Mar/2017:11:46:31 +0000] "POST /1.0/ImportCluster HTTP/1.1" 202 49 0.0193
Mar 08 11:46:31 hostname puma[21396]: 10.34.125.33 - - [08/Mar/2017:11:46:31 +0000] "GET /1.0/jobs/ebd1ac82-ead1-4f68-9336-385e74a62a86 HTTP/1.1" 200 774 0.0186
Mar 08 11:47:07 hostname puma[21396]: 10.40.3.22 - - [08/Mar/2017:11:47:07 +0000] "GET //1.0/jobs HTTP/1.1" 200 776 0.0333
Mar 08 11:47:20 hostname puma[21396]: Net::HTTPRetriableError - 301 "Moved Permanently":
Mar 08 11:47:20 hostname puma[21396]: /usr/share/ruby/net/http/response.rb:119:in `error!'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:145:in `process_http_request'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/tendrl-api/base.rb:106:in `block in <class:Base>'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
Mar 08 11:47:20 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
...skipping...
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
Mar 08 11:50:53 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
Mar 08 11:50:53 hostname puma[21396]: 10.40.3.22 - - [08/Mar/2017:11:50:53 +0000] "GET //1.0/jobs/ebd1ac82-ead1-4f68-9336-385e74a62a86/logs?type=warn HTTP/1.1" 500 30 0.
Mar 08 11:50:57 hostname puma[21396]: Net::HTTPRetriableError - 301 "Moved Permanently":
Mar 08 11:50:57 hostname puma[21396]: /usr/share/ruby/net/http/response.rb:119:in `error!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:145:in `process_http_request'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/tendrl-api/base.rb:106:in `block in <class:Base>'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
Mar 08 11:50:57 hostname puma[21396]: /usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
Mar 08 11:50:57 hostname puma[21396]: 10.40.3.22 - - [08/Mar/2017:11:50:57 +0000] "GET //1.0/jobs/ebd1ac82-ead1-4f68-9336-385e74a62a86/logs HTTP/1.1" 500 30 0.0203
```

**Comment by anivargi** [comment]
@fbalak we will be adapting a new system for logging, so this is irrelevant at this point of time.
